image: openjdk:21-jdk

services:
  - postgres:16

variables:
  POSTGRES_DB: todolist_db
  POSTGRES_USER: todolist_user
  POSTGRES_PASSWORD: todolist_pass
  DATABASE_URL: jdbc:postgresql://postgres:5432/todolist_db
  DATABASE_USERNAME: todolist_user
  DATABASE_PASSWORD: todolist_pass

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./mvnw clean compile
  artifacts:
    paths:
      - target/

test:
  stage: test
  script:
    - ./mvnw test
  artifacts:
    paths:
      - target/surefire-reports/
    when: always
